# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26392f494a34c8b21fd8b1fca3fbe96ad588159f15a6c686be44bd3f69efee3fbe2a9c84746837eafee3ff0f3eb9313eba7ad8f3156eeef4e3b2308e4fcfef58

test:
  secret_key_base: e3fca285d335b8cb7fca119cbfa5e6419d76ada8d4736eab66a529acf70b5707280adfef40a67910f3122c818c5d18bcb5b44ecc57c66c188c92fa7661f734e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
